/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven;

import org.xtext.dsl.multimaven.AbstractMultiMavenRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MultiMavenRuntimeModule extends AbstractMultiMavenRuntimeModule {
}
