/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.ide;

import org.xtext.dsl.multimaven.ide.AbstractMultiMavenIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MultiMavenIdeModule extends AbstractMultiMavenIdeModule {
}
