/*
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MultiMavenStandaloneSetup extends MultiMavenStandaloneSetupGenerated {

	def static void doSetup() {
		new MultiMavenStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
