/*
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.restaurante.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.dsl.restaurante.ui.internal.RestauranteActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RestauranteExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RestauranteActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RestauranteActivator activator = RestauranteActivator.getInstance();
		return activator != null ? activator.getInjector(RestauranteActivator.ORG_XTEXT_DSL_RESTAURANTE_RESTAURANTE) : null;
	}

}
