/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.multiMaven;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependencia</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getGroup <em>Group</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getArtifact <em>Artifact</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getVersion <em>Version</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getScope <em>Scope</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDependencia()
 * @model
 * @generated
 */
public interface Dependencia extends EObject
{
  /**
   * Returns the value of the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group</em>' attribute.
   * @see #setGroup(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDependencia_Group()
   * @model
   * @generated
   */
  String getGroup();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getGroup <em>Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group</em>' attribute.
   * @see #getGroup()
   * @generated
   */
  void setGroup(String value);

  /**
   * Returns the value of the '<em><b>Artifact</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Artifact</em>' attribute.
   * @see #setArtifact(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDependencia_Artifact()
   * @model
   * @generated
   */
  String getArtifact();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getArtifact <em>Artifact</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Artifact</em>' attribute.
   * @see #getArtifact()
   * @generated
   */
  void setArtifact(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDependencia_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Scope</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.dsl.multimaven.multiMaven.Scope}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scope</em>' attribute.
   * @see org.xtext.dsl.multimaven.multiMaven.Scope
   * @see #setScope(Scope)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDependencia_Scope()
   * @model
   * @generated
   */
  Scope getScope();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getScope <em>Scope</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scope</em>' attribute.
   * @see org.xtext.dsl.multimaven.multiMaven.Scope
   * @see #getScope()
   * @generated
   */
  void setScope(Scope value);

} // Dependencia
