/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.multiMaven;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Directorio</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getGroup <em>Group</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getArtifact <em>Artifact</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getVersion <em>Version</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getPackaging <em>Packaging</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getDependencias <em>Dependencias</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getPlugins <em>Plugins</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorio()
 * @model
 * @generated
 */
public interface Directorio extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorio_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group</em>' attribute.
   * @see #setGroup(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorio_Group()
   * @model
   * @generated
   */
  String getGroup();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getGroup <em>Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group</em>' attribute.
   * @see #getGroup()
   * @generated
   */
  void setGroup(String value);

  /**
   * Returns the value of the '<em><b>Artifact</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Artifact</em>' attribute.
   * @see #setArtifact(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorio_Artifact()
   * @model
   * @generated
   */
  String getArtifact();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getArtifact <em>Artifact</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Artifact</em>' attribute.
   * @see #getArtifact()
   * @generated
   */
  void setArtifact(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorio_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Packaging</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.dsl.multimaven.multiMaven.Packaging}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Packaging</em>' attribute.
   * @see org.xtext.dsl.multimaven.multiMaven.Packaging
   * @see #setPackaging(Packaging)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorio_Packaging()
   * @model
   * @generated
   */
  Packaging getPackaging();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getPackaging <em>Packaging</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Packaging</em>' attribute.
   * @see org.xtext.dsl.multimaven.multiMaven.Packaging
   * @see #getPackaging()
   * @generated
   */
  void setPackaging(Packaging value);

  /**
   * Returns the value of the '<em><b>Dependencias</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dsl.multimaven.multiMaven.Dependencia}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependencias</em>' containment reference list.
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorio_Dependencias()
   * @model containment="true"
   * @generated
   */
  EList<Dependencia> getDependencias();

  /**
   * Returns the value of the '<em><b>Plugins</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dsl.multimaven.multiMaven.Plugin}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plugins</em>' containment reference list.
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorio_Plugins()
   * @model containment="true"
   * @generated
   */
  EList<Plugin> getPlugins();

} // Directorio
