/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.multiMaven;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Directorio Padre</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPath <em>Path</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getGroup <em>Group</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getArtifcat <em>Artifcat</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getVersion <em>Version</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPackaging <em>Packaging</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getDependencias <em>Dependencias</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPlugins <em>Plugins</em>}</li>
 *   <li>{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getDirectorios <em>Directorios</em>}</li>
 * </ul>
 *
 * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorioPadre()
 * @model
 * @generated
 */
public interface DirectorioPadre extends EObject
{
  /**
   * Returns the value of the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' attribute.
   * @see #setPath(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorioPadre_Path()
   * @model
   * @generated
   */
  String getPath();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPath <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Path</em>' attribute.
   * @see #getPath()
   * @generated
   */
  void setPath(String value);

  /**
   * Returns the value of the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group</em>' attribute.
   * @see #setGroup(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorioPadre_Group()
   * @model
   * @generated
   */
  String getGroup();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getGroup <em>Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group</em>' attribute.
   * @see #getGroup()
   * @generated
   */
  void setGroup(String value);

  /**
   * Returns the value of the '<em><b>Artifcat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Artifcat</em>' attribute.
   * @see #setArtifcat(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorioPadre_Artifcat()
   * @model
   * @generated
   */
  String getArtifcat();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getArtifcat <em>Artifcat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Artifcat</em>' attribute.
   * @see #getArtifcat()
   * @generated
   */
  void setArtifcat(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorioPadre_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Packaging</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.dsl.multimaven.multiMaven.Packaging}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Packaging</em>' attribute.
   * @see org.xtext.dsl.multimaven.multiMaven.Packaging
   * @see #setPackaging(Packaging)
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorioPadre_Packaging()
   * @model
   * @generated
   */
  Packaging getPackaging();

  /**
   * Sets the value of the '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPackaging <em>Packaging</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Packaging</em>' attribute.
   * @see org.xtext.dsl.multimaven.multiMaven.Packaging
   * @see #getPackaging()
   * @generated
   */
  void setPackaging(Packaging value);

  /**
   * Returns the value of the '<em><b>Dependencias</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dsl.multimaven.multiMaven.Dependencia}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependencias</em>' containment reference list.
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorioPadre_Dependencias()
   * @model containment="true"
   * @generated
   */
  EList<Dependencia> getDependencias();

  /**
   * Returns the value of the '<em><b>Plugins</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dsl.multimaven.multiMaven.Plugin}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plugins</em>' containment reference list.
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorioPadre_Plugins()
   * @model containment="true"
   * @generated
   */
  EList<Plugin> getPlugins();

  /**
   * Returns the value of the '<em><b>Directorios</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dsl.multimaven.multiMaven.Directorio}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Directorios</em>' containment reference list.
   * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getDirectorioPadre_Directorios()
   * @model containment="true"
   * @generated
   */
  EList<Directorio> getDirectorios();

} // DirectorioPadre
