/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.multiMaven;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage
 * @generated
 */
public interface MultiMavenFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MultiMavenFactory eINSTANCE = org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Proyecto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Proyecto</em>'.
   * @generated
   */
  Proyecto createProyecto();

  /**
   * Returns a new object of class '<em>Directorio Padre</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Directorio Padre</em>'.
   * @generated
   */
  DirectorioPadre createDirectorioPadre();

  /**
   * Returns a new object of class '<em>Directorio</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Directorio</em>'.
   * @generated
   */
  Directorio createDirectorio();

  /**
   * Returns a new object of class '<em>Dependencia</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dependencia</em>'.
   * @generated
   */
  Dependencia createDependencia();

  /**
   * Returns a new object of class '<em>Plugin</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Plugin</em>'.
   * @generated
   */
  Plugin createPlugin();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MultiMavenPackage getMultiMavenPackage();

} //MultiMavenFactory
