/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.multiMaven;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenFactory
 * @model kind="package"
 * @generated
 */
public interface MultiMavenPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "multiMaven";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/dsl/multimaven/MultiMaven";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "multiMaven";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MultiMavenPackage eINSTANCE = org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.dsl.multimaven.multiMaven.impl.ProyectoImpl <em>Proyecto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.multimaven.multiMaven.impl.ProyectoImpl
   * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getProyecto()
   * @generated
   */
  int PROYECTO = 0;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROYECTO__VERSION = 0;

  /**
   * The feature id for the '<em><b>Padre</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROYECTO__PADRE = 1;

  /**
   * The number of structural features of the '<em>Proyecto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROYECTO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.dsl.multimaven.multiMaven.impl.DirectorioPadreImpl <em>Directorio Padre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.multimaven.multiMaven.impl.DirectorioPadreImpl
   * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getDirectorioPadre()
   * @generated
   */
  int DIRECTORIO_PADRE = 1;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO_PADRE__PATH = 0;

  /**
   * The feature id for the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO_PADRE__GROUP = 1;

  /**
   * The feature id for the '<em><b>Artifcat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO_PADRE__ARTIFCAT = 2;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO_PADRE__VERSION = 3;

  /**
   * The feature id for the '<em><b>Packaging</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO_PADRE__PACKAGING = 4;

  /**
   * The feature id for the '<em><b>Dependencias</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO_PADRE__DEPENDENCIAS = 5;

  /**
   * The feature id for the '<em><b>Plugins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO_PADRE__PLUGINS = 6;

  /**
   * The feature id for the '<em><b>Directorios</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO_PADRE__DIRECTORIOS = 7;

  /**
   * The number of structural features of the '<em>Directorio Padre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO_PADRE_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.dsl.multimaven.multiMaven.impl.DirectorioImpl <em>Directorio</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.multimaven.multiMaven.impl.DirectorioImpl
   * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getDirectorio()
   * @generated
   */
  int DIRECTORIO = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO__NAME = 0;

  /**
   * The feature id for the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO__GROUP = 1;

  /**
   * The feature id for the '<em><b>Artifcat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO__ARTIFCAT = 2;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO__VERSION = 3;

  /**
   * The feature id for the '<em><b>Packaging</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO__PACKAGING = 4;

  /**
   * The feature id for the '<em><b>Dependencias</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO__DEPENDENCIAS = 5;

  /**
   * The feature id for the '<em><b>Plugins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO__PLUGINS = 6;

  /**
   * The number of structural features of the '<em>Directorio</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECTORIO_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.dsl.multimaven.multiMaven.impl.DependenciaImpl <em>Dependencia</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.multimaven.multiMaven.impl.DependenciaImpl
   * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getDependencia()
   * @generated
   */
  int DEPENDENCIA = 3;

  /**
   * The feature id for the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCIA__GROUP = 0;

  /**
   * The feature id for the '<em><b>Artifcat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCIA__ARTIFCAT = 1;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCIA__VERSION = 2;

  /**
   * The feature id for the '<em><b>Scope</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCIA__SCOPE = 3;

  /**
   * The number of structural features of the '<em>Dependencia</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCIA_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.dsl.multimaven.multiMaven.impl.PluginImpl <em>Plugin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.multimaven.multiMaven.impl.PluginImpl
   * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getPlugin()
   * @generated
   */
  int PLUGIN = 4;

  /**
   * The feature id for the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUGIN__GROUP = 0;

  /**
   * The feature id for the '<em><b>Artifcat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUGIN__ARTIFCAT = 1;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUGIN__VERSION = 2;

  /**
   * The number of structural features of the '<em>Plugin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUGIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.dsl.multimaven.multiMaven.Packaging <em>Packaging</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.multimaven.multiMaven.Packaging
   * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getPackaging()
   * @generated
   */
  int PACKAGING = 5;

  /**
   * The meta object id for the '{@link org.xtext.dsl.multimaven.multiMaven.Scope <em>Scope</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.multimaven.multiMaven.Scope
   * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getScope()
   * @generated
   */
  int SCOPE = 6;


  /**
   * Returns the meta object for class '{@link org.xtext.dsl.multimaven.multiMaven.Proyecto <em>Proyecto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Proyecto</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Proyecto
   * @generated
   */
  EClass getProyecto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Proyecto#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Proyecto#getVersion()
   * @see #getProyecto()
   * @generated
   */
  EAttribute getProyecto_Version();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.dsl.multimaven.multiMaven.Proyecto#getPadre <em>Padre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Padre</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Proyecto#getPadre()
   * @see #getProyecto()
   * @generated
   */
  EReference getProyecto_Padre();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre <em>Directorio Padre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Directorio Padre</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.DirectorioPadre
   * @generated
   */
  EClass getDirectorioPadre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPath()
   * @see #getDirectorioPadre()
   * @generated
   */
  EAttribute getDirectorioPadre_Path();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getGroup <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Group</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getGroup()
   * @see #getDirectorioPadre()
   * @generated
   */
  EAttribute getDirectorioPadre_Group();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getArtifcat <em>Artifcat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Artifcat</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getArtifcat()
   * @see #getDirectorioPadre()
   * @generated
   */
  EAttribute getDirectorioPadre_Artifcat();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getVersion()
   * @see #getDirectorioPadre()
   * @generated
   */
  EAttribute getDirectorioPadre_Version();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPackaging <em>Packaging</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Packaging</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPackaging()
   * @see #getDirectorioPadre()
   * @generated
   */
  EAttribute getDirectorioPadre_Packaging();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getDependencias <em>Dependencias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dependencias</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getDependencias()
   * @see #getDirectorioPadre()
   * @generated
   */
  EReference getDirectorioPadre_Dependencias();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPlugins <em>Plugins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Plugins</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getPlugins()
   * @see #getDirectorioPadre()
   * @generated
   */
  EReference getDirectorioPadre_Plugins();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getDirectorios <em>Directorios</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Directorios</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.DirectorioPadre#getDirectorios()
   * @see #getDirectorioPadre()
   * @generated
   */
  EReference getDirectorioPadre_Directorios();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.multimaven.multiMaven.Directorio <em>Directorio</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Directorio</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Directorio
   * @generated
   */
  EClass getDirectorio();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Directorio#getName()
   * @see #getDirectorio()
   * @generated
   */
  EAttribute getDirectorio_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getGroup <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Group</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Directorio#getGroup()
   * @see #getDirectorio()
   * @generated
   */
  EAttribute getDirectorio_Group();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getArtifcat <em>Artifcat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Artifcat</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Directorio#getArtifcat()
   * @see #getDirectorio()
   * @generated
   */
  EAttribute getDirectorio_Artifcat();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Directorio#getVersion()
   * @see #getDirectorio()
   * @generated
   */
  EAttribute getDirectorio_Version();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getPackaging <em>Packaging</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Packaging</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Directorio#getPackaging()
   * @see #getDirectorio()
   * @generated
   */
  EAttribute getDirectorio_Packaging();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getDependencias <em>Dependencias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dependencias</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Directorio#getDependencias()
   * @see #getDirectorio()
   * @generated
   */
  EReference getDirectorio_Dependencias();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.multimaven.multiMaven.Directorio#getPlugins <em>Plugins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Plugins</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Directorio#getPlugins()
   * @see #getDirectorio()
   * @generated
   */
  EReference getDirectorio_Plugins();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.multimaven.multiMaven.Dependencia <em>Dependencia</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependencia</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Dependencia
   * @generated
   */
  EClass getDependencia();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getGroup <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Group</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Dependencia#getGroup()
   * @see #getDependencia()
   * @generated
   */
  EAttribute getDependencia_Group();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getArtifcat <em>Artifcat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Artifcat</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Dependencia#getArtifcat()
   * @see #getDependencia()
   * @generated
   */
  EAttribute getDependencia_Artifcat();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Dependencia#getVersion()
   * @see #getDependencia()
   * @generated
   */
  EAttribute getDependencia_Version();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Dependencia#getScope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Scope</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Dependencia#getScope()
   * @see #getDependencia()
   * @generated
   */
  EAttribute getDependencia_Scope();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.multimaven.multiMaven.Plugin <em>Plugin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plugin</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Plugin
   * @generated
   */
  EClass getPlugin();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Plugin#getGroup <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Group</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Plugin#getGroup()
   * @see #getPlugin()
   * @generated
   */
  EAttribute getPlugin_Group();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Plugin#getArtifcat <em>Artifcat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Artifcat</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Plugin#getArtifcat()
   * @see #getPlugin()
   * @generated
   */
  EAttribute getPlugin_Artifcat();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.multimaven.multiMaven.Plugin#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Plugin#getVersion()
   * @see #getPlugin()
   * @generated
   */
  EAttribute getPlugin_Version();

  /**
   * Returns the meta object for enum '{@link org.xtext.dsl.multimaven.multiMaven.Packaging <em>Packaging</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Packaging</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Packaging
   * @generated
   */
  EEnum getPackaging();

  /**
   * Returns the meta object for enum '{@link org.xtext.dsl.multimaven.multiMaven.Scope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Scope</em>'.
   * @see org.xtext.dsl.multimaven.multiMaven.Scope
   * @generated
   */
  EEnum getScope();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MultiMavenFactory getMultiMavenFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.dsl.multimaven.multiMaven.impl.ProyectoImpl <em>Proyecto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.multimaven.multiMaven.impl.ProyectoImpl
     * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getProyecto()
     * @generated
     */
    EClass PROYECTO = eINSTANCE.getProyecto();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROYECTO__VERSION = eINSTANCE.getProyecto_Version();

    /**
     * The meta object literal for the '<em><b>Padre</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROYECTO__PADRE = eINSTANCE.getProyecto_Padre();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.multimaven.multiMaven.impl.DirectorioPadreImpl <em>Directorio Padre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.multimaven.multiMaven.impl.DirectorioPadreImpl
     * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getDirectorioPadre()
     * @generated
     */
    EClass DIRECTORIO_PADRE = eINSTANCE.getDirectorioPadre();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTORIO_PADRE__PATH = eINSTANCE.getDirectorioPadre_Path();

    /**
     * The meta object literal for the '<em><b>Group</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTORIO_PADRE__GROUP = eINSTANCE.getDirectorioPadre_Group();

    /**
     * The meta object literal for the '<em><b>Artifcat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTORIO_PADRE__ARTIFCAT = eINSTANCE.getDirectorioPadre_Artifcat();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTORIO_PADRE__VERSION = eINSTANCE.getDirectorioPadre_Version();

    /**
     * The meta object literal for the '<em><b>Packaging</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTORIO_PADRE__PACKAGING = eINSTANCE.getDirectorioPadre_Packaging();

    /**
     * The meta object literal for the '<em><b>Dependencias</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTORIO_PADRE__DEPENDENCIAS = eINSTANCE.getDirectorioPadre_Dependencias();

    /**
     * The meta object literal for the '<em><b>Plugins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTORIO_PADRE__PLUGINS = eINSTANCE.getDirectorioPadre_Plugins();

    /**
     * The meta object literal for the '<em><b>Directorios</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTORIO_PADRE__DIRECTORIOS = eINSTANCE.getDirectorioPadre_Directorios();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.multimaven.multiMaven.impl.DirectorioImpl <em>Directorio</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.multimaven.multiMaven.impl.DirectorioImpl
     * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getDirectorio()
     * @generated
     */
    EClass DIRECTORIO = eINSTANCE.getDirectorio();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTORIO__NAME = eINSTANCE.getDirectorio_Name();

    /**
     * The meta object literal for the '<em><b>Group</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTORIO__GROUP = eINSTANCE.getDirectorio_Group();

    /**
     * The meta object literal for the '<em><b>Artifcat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTORIO__ARTIFCAT = eINSTANCE.getDirectorio_Artifcat();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTORIO__VERSION = eINSTANCE.getDirectorio_Version();

    /**
     * The meta object literal for the '<em><b>Packaging</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECTORIO__PACKAGING = eINSTANCE.getDirectorio_Packaging();

    /**
     * The meta object literal for the '<em><b>Dependencias</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTORIO__DEPENDENCIAS = eINSTANCE.getDirectorio_Dependencias();

    /**
     * The meta object literal for the '<em><b>Plugins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIRECTORIO__PLUGINS = eINSTANCE.getDirectorio_Plugins();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.multimaven.multiMaven.impl.DependenciaImpl <em>Dependencia</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.multimaven.multiMaven.impl.DependenciaImpl
     * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getDependencia()
     * @generated
     */
    EClass DEPENDENCIA = eINSTANCE.getDependencia();

    /**
     * The meta object literal for the '<em><b>Group</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCIA__GROUP = eINSTANCE.getDependencia_Group();

    /**
     * The meta object literal for the '<em><b>Artifcat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCIA__ARTIFCAT = eINSTANCE.getDependencia_Artifcat();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCIA__VERSION = eINSTANCE.getDependencia_Version();

    /**
     * The meta object literal for the '<em><b>Scope</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCIA__SCOPE = eINSTANCE.getDependencia_Scope();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.multimaven.multiMaven.impl.PluginImpl <em>Plugin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.multimaven.multiMaven.impl.PluginImpl
     * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getPlugin()
     * @generated
     */
    EClass PLUGIN = eINSTANCE.getPlugin();

    /**
     * The meta object literal for the '<em><b>Group</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLUGIN__GROUP = eINSTANCE.getPlugin_Group();

    /**
     * The meta object literal for the '<em><b>Artifcat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLUGIN__ARTIFCAT = eINSTANCE.getPlugin_Artifcat();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PLUGIN__VERSION = eINSTANCE.getPlugin_Version();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.multimaven.multiMaven.Packaging <em>Packaging</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.multimaven.multiMaven.Packaging
     * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getPackaging()
     * @generated
     */
    EEnum PACKAGING = eINSTANCE.getPackaging();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.multimaven.multiMaven.Scope <em>Scope</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.multimaven.multiMaven.Scope
     * @see org.xtext.dsl.multimaven.multiMaven.impl.MultiMavenPackageImpl#getScope()
     * @generated
     */
    EEnum SCOPE = eINSTANCE.getScope();

  }

} //MultiMavenPackage
