/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.multiMaven;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Packaging</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.dsl.multimaven.multiMaven.MultiMavenPackage#getPackaging()
 * @model
 * @generated
 */
public enum Packaging implements Enumerator
{
  /**
   * The '<em><b>POM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #POM_VALUE
   * @generated
   * @ordered
   */
  POM(0, "POM", "POM"),

  /**
   * The '<em><b>JAR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JAR_VALUE
   * @generated
   * @ordered
   */
  JAR(1, "JAR", "JAR"),

  /**
   * The '<em><b>EAR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EAR_VALUE
   * @generated
   * @ordered
   */
  EAR(2, "EAR", "EAR"),

  /**
   * The '<em><b>WAR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WAR_VALUE
   * @generated
   * @ordered
   */
  WAR(3, "WAR", "WAR"),

  /**
   * The '<em><b>RAR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RAR_VALUE
   * @generated
   * @ordered
   */
  RAR(4, "RAR", "RAR"),

  /**
   * The '<em><b>MAVENPLUGIN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAVENPLUGIN_VALUE
   * @generated
   * @ordered
   */
  MAVENPLUGIN(5, "MAVENPLUGIN", "MAVENPLUGIN"),

  /**
   * The '<em><b>EJB</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EJB_VALUE
   * @generated
   * @ordered
   */
  EJB(6, "EJB", "EJB");

  /**
   * The '<em><b>POM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #POM
   * @model
   * @generated
   * @ordered
   */
  public static final int POM_VALUE = 0;

  /**
   * The '<em><b>JAR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #JAR
   * @model
   * @generated
   * @ordered
   */
  public static final int JAR_VALUE = 1;

  /**
   * The '<em><b>EAR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EAR
   * @model
   * @generated
   * @ordered
   */
  public static final int EAR_VALUE = 2;

  /**
   * The '<em><b>WAR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WAR
   * @model
   * @generated
   * @ordered
   */
  public static final int WAR_VALUE = 3;

  /**
   * The '<em><b>RAR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RAR
   * @model
   * @generated
   * @ordered
   */
  public static final int RAR_VALUE = 4;

  /**
   * The '<em><b>MAVENPLUGIN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAVENPLUGIN
   * @model
   * @generated
   * @ordered
   */
  public static final int MAVENPLUGIN_VALUE = 5;

  /**
   * The '<em><b>EJB</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EJB
   * @model
   * @generated
   * @ordered
   */
  public static final int EJB_VALUE = 6;

  /**
   * An array of all the '<em><b>Packaging</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Packaging[] VALUES_ARRAY =
    new Packaging[]
    {
      POM,
      JAR,
      EAR,
      WAR,
      RAR,
      MAVENPLUGIN,
      EJB,
    };

  /**
   * A public read-only list of all the '<em><b>Packaging</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Packaging> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Packaging</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Packaging get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Packaging result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Packaging</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Packaging getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Packaging result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Packaging</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Packaging get(int value)
  {
    switch (value)
    {
      case POM_VALUE: return POM;
      case JAR_VALUE: return JAR;
      case EAR_VALUE: return EAR;
      case WAR_VALUE: return WAR;
      case RAR_VALUE: return RAR;
      case MAVENPLUGIN_VALUE: return MAVENPLUGIN;
      case EJB_VALUE: return EJB;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Packaging(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Packaging
