/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.restaurante.ide;

import org.xtext.dsl.restaurante.ide.AbstractRestauranteIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RestauranteIdeModule extends AbstractRestauranteIdeModule {
}
