/*
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MultiMavenAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/dsl/multimaven/parser/antlr/internal/InternalMultiMaven.tokens");
	}
}
