/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.restaurante.restaurante;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.dsl.restaurante.restaurante.RestauranteFactory
 * @model kind="package"
 * @generated
 */
public interface RestaurantePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "restaurante";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/dsl/restaurante/Restaurante";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "restaurante";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  RestaurantePackage eINSTANCE = org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.RestauranteImpl <em>Restaurante</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestauranteImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getRestaurante()
   * @generated
   */
  int RESTAURANTE = 0;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANTE__NOMBRE = 0;

  /**
   * The feature id for the '<em><b>Fecha</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANTE__FECHA = 1;

  /**
   * The feature id for the '<em><b>Ingredientes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANTE__INGREDIENTES = 2;

  /**
   * The number of structural features of the '<em>Restaurante</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESTAURANTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl <em>Ingrediente</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl
   * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getIngrediente()
   * @generated
   */
  int INGREDIENTE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Nombre</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__NOMBRE = 1;

  /**
   * The feature id for the '<em><b>Info URL</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__INFO_URL = 2;

  /**
   * The feature id for the '<em><b>Foto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__FOTO = 3;

  /**
   * The feature id for the '<em><b>Alergenico</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE__ALERGENICO = 4;

  /**
   * The number of structural features of the '<em>Ingrediente</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGREDIENTE_FEATURE_COUNT = 5;


  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Restaurante <em>Restaurante</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Restaurante</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Restaurante
   * @generated
   */
  EClass getRestaurante();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Restaurante#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Restaurante#getNombre()
   * @see #getRestaurante()
   * @generated
   */
  EAttribute getRestaurante_Nombre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Restaurante#getFecha <em>Fecha</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fecha</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Restaurante#getFecha()
   * @see #getRestaurante()
   * @generated
   */
  EAttribute getRestaurante_Fecha();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.dsl.restaurante.restaurante.Restaurante#getIngredientes <em>Ingredientes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ingredientes</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Restaurante#getIngredientes()
   * @see #getRestaurante()
   * @generated
   */
  EReference getRestaurante_Ingredientes();

  /**
   * Returns the meta object for class '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente <em>Ingrediente</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ingrediente</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente
   * @generated
   */
  EClass getIngrediente();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente#getName()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente#getNombre <em>Nombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nombre</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente#getNombre()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Nombre();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente#getInfoURL <em>Info URL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Info URL</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente#getInfoURL()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_InfoURL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente#getFoto <em>Foto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Foto</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente#getFoto()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Foto();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.dsl.restaurante.restaurante.Ingrediente#isAlergenico <em>Alergenico</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alergenico</em>'.
   * @see org.xtext.dsl.restaurante.restaurante.Ingrediente#isAlergenico()
   * @see #getIngrediente()
   * @generated
   */
  EAttribute getIngrediente_Alergenico();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  RestauranteFactory getRestauranteFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.RestauranteImpl <em>Restaurante</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestauranteImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getRestaurante()
     * @generated
     */
    EClass RESTAURANTE = eINSTANCE.getRestaurante();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESTAURANTE__NOMBRE = eINSTANCE.getRestaurante_Nombre();

    /**
     * The meta object literal for the '<em><b>Fecha</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESTAURANTE__FECHA = eINSTANCE.getRestaurante_Fecha();

    /**
     * The meta object literal for the '<em><b>Ingredientes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESTAURANTE__INGREDIENTES = eINSTANCE.getRestaurante_Ingredientes();

    /**
     * The meta object literal for the '{@link org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl <em>Ingrediente</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.dsl.restaurante.restaurante.impl.IngredienteImpl
     * @see org.xtext.dsl.restaurante.restaurante.impl.RestaurantePackageImpl#getIngrediente()
     * @generated
     */
    EClass INGREDIENTE = eINSTANCE.getIngrediente();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__NAME = eINSTANCE.getIngrediente_Name();

    /**
     * The meta object literal for the '<em><b>Nombre</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__NOMBRE = eINSTANCE.getIngrediente_Nombre();

    /**
     * The meta object literal for the '<em><b>Info URL</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__INFO_URL = eINSTANCE.getIngrediente_InfoURL();

    /**
     * The meta object literal for the '<em><b>Foto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__FOTO = eINSTANCE.getIngrediente_Foto();

    /**
     * The meta object literal for the '<em><b>Alergenico</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGREDIENTE__ALERGENICO = eINSTANCE.getIngrediente_Alergenico();

  }

} //RestaurantePackage
