/*
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MultiMavenWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMultiMavenWebModule extends DefaultWebModule {

}
