/*
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.dsl.multimaven.ui.internal.MultimavenActivator;

public class MultiMavenUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MultimavenActivator.getInstance().getInjector("org.xtext.dsl.multimaven.MultiMaven");
	}

}
