/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.restaurante.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.dsl.restaurante.ui.AbstractRestauranteUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RestauranteUiModule extends AbstractRestauranteUiModule {
  public RestauranteUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
