/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.dsl.multimaven.ui.AbstractMultiMavenUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MultiMavenUiModule extends AbstractMultiMavenUiModule {
  public MultiMavenUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
