/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.web;

import org.xtext.dsl.multimaven.web.AbstractMultiMavenWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class MultiMavenWebModule extends AbstractMultiMavenWebModule {
}
