/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.restaurante.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.xtext.dsl.restaurante.restaurante.Ingrediente;
import org.xtext.dsl.restaurante.restaurante.Restaurante;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class RestauranteLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public RestauranteLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String image(final Restaurante r) {
    return "restaurante.ico";
  }
  
  public String image(final Ingrediente i) {
    return "ingrediente.ico";
  }
  
  public String text(final Ingrediente i) {
    String _name = i.getName();
    String _plus = ("Ingrediente " + _name);
    String _plus_1 = (_plus + " (");
    String _nombre = i.getNombre();
    String _plus_2 = (_plus_1 + _nombre);
    return (_plus_2 + ")");
  }
}
