/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.restaurante.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.dsl.restaurante.restaurante.Ingrediente;
import org.xtext.dsl.restaurante.restaurante.RestaurantePackage;
import org.xtext.dsl.restaurante.validation.AbstractRestauranteValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RestauranteValidator extends AbstractRestauranteValidator {
  public static final String INVALID_NAME = "invalidName";
  
  @Check
  public void checkAtributesMoreThan20(final Ingrediente ingrediente) {
    int _length = ingrediente.getNombre().length();
    boolean _greaterEqualsThan = (_length >= 20);
    if (_greaterEqualsThan) {
      this.warning("El nombre debería tener menos de 20 caracteres", 
        RestaurantePackage.Literals.INGREDIENTE__NAME, RestauranteValidator.INVALID_NAME);
    }
  }
}
