/*
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMultiMavenScopeProvider extends DelegatingScopeProvider {
}
