/*
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.multimaven.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class MultiMavenWebModule extends AbstractMultiMavenWebModule {
}
