/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.restaurante.ui.quickfix;

import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.xtext.dsl.restaurante.validation.RestauranteValidator;

/**
 * Custom quickfixes.
 * 
 * See https:www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class RestauranteQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(RestauranteValidator.INVALID_NAME)
  public void arreglarNombre(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext context) -> {
      final IXtextDocument xtextDocument = context.getXtextDocument();
      final String nombreActual = xtextDocument.get((issue.getOffset()).intValue(), (issue.getLength()).intValue());
      Integer _offset = issue.getOffset();
      Integer _length = issue.getLength();
      String _substring = nombreActual.substring(0, 18);
      String _plus = (_substring + "\'");
      xtextDocument.replace((_offset).intValue(), (_length).intValue(), _plus);
    };
    acceptor.accept(issue, "Reducir nombre", "Se limitará el tamaño de nombre al máximo sugerido", "ingrediente.ico", _function);
  }
}
