/*
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.restaurante.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link RestauranteWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractRestauranteWebModule extends DefaultWebModule {

}
