/**
 * generated by Xtext 2.19.0
 */
package org.xtext.dsl.restaurante.restaurante.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.dsl.restaurante.restaurante.Ingrediente;
import org.xtext.dsl.restaurante.restaurante.Restaurante;
import org.xtext.dsl.restaurante.restaurante.RestauranteFactory;
import org.xtext.dsl.restaurante.restaurante.RestaurantePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class RestaurantePackageImpl extends EPackageImpl implements RestaurantePackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass restauranteEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ingredienteEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.dsl.restaurante.restaurante.RestaurantePackage#eNS_URI
   * @see #init()
   * @generated
   */
  private RestaurantePackageImpl()
  {
    super(eNS_URI, RestauranteFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link RestaurantePackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static RestaurantePackage init()
  {
    if (isInited) return (RestaurantePackage)EPackage.Registry.INSTANCE.getEPackage(RestaurantePackage.eNS_URI);

    // Obtain or create and register package
    Object registeredRestaurantePackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    RestaurantePackageImpl theRestaurantePackage = registeredRestaurantePackage instanceof RestaurantePackageImpl ? (RestaurantePackageImpl)registeredRestaurantePackage : new RestaurantePackageImpl();

    isInited = true;

    // Create package meta-data objects
    theRestaurantePackage.createPackageContents();

    // Initialize created meta-data
    theRestaurantePackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theRestaurantePackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(RestaurantePackage.eNS_URI, theRestaurantePackage);
    return theRestaurantePackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRestaurante()
  {
    return restauranteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRestaurante_Nombre()
  {
    return (EAttribute)restauranteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRestaurante_Fecha()
  {
    return (EAttribute)restauranteEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getRestaurante_Ingredientes()
  {
    return (EReference)restauranteEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIngrediente()
  {
    return ingredienteEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIngrediente_Name()
  {
    return (EAttribute)ingredienteEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIngrediente_Nombre()
  {
    return (EAttribute)ingredienteEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIngrediente_InfoURL()
  {
    return (EAttribute)ingredienteEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIngrediente_Foto()
  {
    return (EAttribute)ingredienteEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIngrediente_Alergenico()
  {
    return (EAttribute)ingredienteEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RestauranteFactory getRestauranteFactory()
  {
    return (RestauranteFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    restauranteEClass = createEClass(RESTAURANTE);
    createEAttribute(restauranteEClass, RESTAURANTE__NOMBRE);
    createEAttribute(restauranteEClass, RESTAURANTE__FECHA);
    createEReference(restauranteEClass, RESTAURANTE__INGREDIENTES);

    ingredienteEClass = createEClass(INGREDIENTE);
    createEAttribute(ingredienteEClass, INGREDIENTE__NAME);
    createEAttribute(ingredienteEClass, INGREDIENTE__NOMBRE);
    createEAttribute(ingredienteEClass, INGREDIENTE__INFO_URL);
    createEAttribute(ingredienteEClass, INGREDIENTE__FOTO);
    createEAttribute(ingredienteEClass, INGREDIENTE__ALERGENICO);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(restauranteEClass, Restaurante.class, "Restaurante", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRestaurante_Nombre(), ecorePackage.getEString(), "nombre", null, 0, 1, Restaurante.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRestaurante_Fecha(), ecorePackage.getEString(), "fecha", null, 0, 1, Restaurante.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRestaurante_Ingredientes(), this.getIngrediente(), null, "ingredientes", null, 0, -1, Restaurante.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ingredienteEClass, Ingrediente.class, "Ingrediente", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIngrediente_Name(), ecorePackage.getEString(), "name", null, 0, 1, Ingrediente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIngrediente_Nombre(), ecorePackage.getEString(), "nombre", null, 0, 1, Ingrediente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIngrediente_InfoURL(), ecorePackage.getEString(), "infoURL", null, 0, 1, Ingrediente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIngrediente_Foto(), ecorePackage.getEString(), "foto", null, 0, 1, Ingrediente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIngrediente_Alergenico(), ecorePackage.getEBoolean(), "alergenico", null, 0, 1, Ingrediente.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //RestaurantePackageImpl
